# Generated by Django 5.1.11 on 2026-07-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['student_department']},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='student_department',
        ),
    ]
